version: 2.1

jobs:
  buildImage:
    machine: true     
   
    steps:
      - checkout
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

      - run: docker build -t dmaxim/messageapi:v1.0 -f src/circle-Dockerfile .

      - run: docker push dmaxim/messagepi:v1.0
